driver: sim
visual:
  show: true
  animate: true
  title: "SVG draw demo"
  fps: 75

defaults:
  unit: mm
  mode: absolute
  feed: 1200

jobs:
  - type: svg
    file:                  # 空にするとファイル選択ダイアログが表示されます
    origin: [0, 0]         # 左下オフセット(mm)
    px_to_mm: 0.264583     # 96dpiの換算 (必要に応じて微調整)
    chord_mm: 0.5          # サンプリング間隔(mm) 小さいほど滑らか
    feed: 1000             # 送り
    y_flip: false          # 機械座標がYアップなら true にして svg_height_mm を与える
    # svg_height_mm: 210   # 例: A4縦のとき 297mm 等 (y_flip時のみ必要)
    sort_paths: true       # 経路をざっくり並べ替えて無駄移動を少し減らす
